// Generated by Wrangler by running `wrangler types`

interface Env {
	ORDER_SYNC: DurableObjectNamespace<import("./src/worker").OrderSync>;
	ORDERING_SYSTEM_BUCKET: R2Bucket;
	DB: D1Database;
	WORKER_SELF_REFERENCE: Fetcher;
	ASSETS: Fetcher;
}
