// Generated by Wrangler by running `wrangler types`

interface Env {
	ORDER_SYNC: DurableObjectNamespace<import("./src/worker").OrderSync>;
	DB: D1Database;
	WORKER_SELF_REFERENCE: Fetcher;
	ASSETS: Fetcher;
}
